name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'GNUmakefile'
      - '.goreleaser.yml'
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'GNUmakefile'
      - '.goreleaser.yml'
      - '.github/workflows/nightly-test.yaml'
      - '.github/workflows/release.yaml'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest

  generate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: '~1.5.0'
          terraform_wrapper: false
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  testunit:
    name: Unit tests
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go test $(go list ./... | egrep -v '/internal/provider$')

  testacc:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        terraform:
          - '1.5.*'
          - '1.6.*'
          - '1.12.*'
          - '1.13.*'
          - '1.14.*'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: go test -v -cover ./internal/provider/
        timeout-minutes: 15
        env:
          TF_ACC: "1"
          BUNNYNET_API_KEY: ${{ secrets.TESTACC_API_KEY }}
          TESTACC_MC_REGION: ${{ vars.TESTACC_MC_REGION_PROD }}
